services:
  coordinator:
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile
      target: coordinator
    volumes:
      - ./configs/single/coordinator.yaml:/app/deploy/configs/coordinator.yaml:ro
      - coordinator_single_data:/app/data
    ports:
      - "9000:9000"
    networks:
      - back

  volume-a:
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile
      target: volume
    volumes:
      - ./configs/single/volume-a.yaml:/app/deploy/configs/volume.yaml:ro
      - volume_a_single_data:/app/data
    networks:
      - back

  volume-b:
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile
      target: volume
    volumes:
      - ./configs/single/volume-b.yaml:/app/deploy/configs/volume.yaml:ro
      - volume_b_single_data:/app/data
    networks:
      - back

  volume-c:
    build:
      context: ..
      dockerfile: deploy/docker/Dockerfile
      target: volume
    volumes:
      - ./configs/single/volume-c.yaml:/app/deploy/configs/volume.yaml:ro
      - volume_c_single_data:/app/data
    networks:
      - back

networks:
  back:

volumes:
  coordinator_single_data:
  volume_a_single_data:
  volume_b_single_data:
  volume_c_single_data:
